# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: schemacrawler.schemacrawler
PackageVersion: 16.16.11
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/schemacrawler/SchemaCrawler-Installers/releases/download/v16.16.11/SchemaCrawler-16.16.11.msi
  InstallerSha256: 0762818EBF0400DE934BCD436972989EB49891A1532A594F1711F712336147C9
  ProductCode: '{A9EB246D-FA86-393E-87B0-9C01B07B1D89}'
ManifestType: installer
ManifestVersion: 1.0.0

