PackageIdentifier: BraveSoftware.BraveBrowser.Dev
PackageVersion: 98.1.36.84
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: ' '
  SilentWithProgress: ' '
UpgradeBehavior: install
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.36.84/BraveBrowserStandaloneSilentDevSetup.exe
  InstallerSha256: 6F652FE37C9CCDF2B3D891867ECEBA2FE801C4E0E219C0EE282A11C458A7D1DF
ManifestType: installer
ManifestVersion: 1.1.0
