# Automatically updated by the winget bot at 2022/Feb/07
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: GeoGebra.GraphingCalculator
PackageVersion: 6.0.687
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://download.geogebra.org/package/windows-graphing
  InstallerSha256: C780645F6A55A67A9E1C6DE30B2CFDD732694F613D6B9D917DB50246DF7B3F20
ManifestType: installer
ManifestVersion: 1.0.0
