# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=AUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome.Beta
PackageVersion: 99.0.4844.27
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 6F24A85D11378B2E38B74424A43E78A505A1B826A09668C83AD0E6D6AB2A8EFE
  ProductCode: '{B02797C4-427A-39FE-9CCA-9DAF1550287D}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 97715042A7DA78C706AF1A638FF56EF731C54EC222C3DD9DD6FB5120589BA91F
  ProductCode: '{70D95759-1EAC-3C7A-9BFE-56E13C2DBE2C}'
ManifestType: installer
ManifestVersion: 1.1.0
