# Created with YamlCreate.ps1 v2.0.6 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: ojdkbuild.ojdkbuild
PackageVersion: 11.0.7.1
PackageLocale: en-US
Publisher: ojdkbuild open-source project
PublisherUrl: https://github.com/ojdkbuild/ojdkbuild
PublisherSupportUrl: https://github.com/ojdkbuild/ojdkbuild/issues
# PrivacyUrl: 
Author: Alex Kashchenko
PackageName: OpenJDK 11.0.7-1-ojdkbuild
PackageUrl: https://github.com/ojdkbuild/ojdkbuild/wiki/Motivation
License: GPL 2 with Classpath Exception
LicenseUrl: https://github.com/ojdkbuild/ojdkbuild/blob/master/LICENSE
# Copyright: 
# CopyrightUrl: 
ShortDescription: Community builds using source code from OpenJDK project
# Description: 
# Moniker: 
# Tags: 
# Agreements: 
# ReleaseNotes: 
ReleaseNotesUrl: https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-11-openjdk-11.0.7.10-1
ManifestType: defaultLocale
ManifestVersion: 1.1.0
