# Automatically updated by the winget bot at 2022/Feb/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: WhatsApp.WhatsApp.Beta
PackageVersion: 2.2204.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/x64/WhatsAppSetup-beta.exe
  InstallerSha256: 0B10B23C35186EE6E27FEB1C7E743F127E99FABA9CD70BD72E522CBD205D2B41
- Architecture: x86
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/ia32/WhatsAppSetup-beta.exe
  InstallerSha256: 8446DDEFB9DFF11AFE7AEDE0BD8BF518CA99575E6250100210CC779972B98807
ManifestType: installer
ManifestVersion: 1.1.0
