# Created with YamlCreate.ps1 v2.0.6 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: VPNetwork.TorGuard
PackageVersion: 4.8.8-build.136.1+gfd6b5ad
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://torguard.net/downloads/new/torguard-setup-latest.exe
  InstallerSha256: BD7A84F1F8E61F4333E485DBBBF859520DECF8449D5C41D6AF39E3A6346C9707
  ProductCode: VPNetwork LLC TorGuard
ManifestType: installer
ManifestVersion: 1.1.0
