# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=AUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 98.0.4758.82
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 6A6ACE909770E8F177542BFEA9A873264AA60E0CF295FCF1755D6F19D08B3DA8
  ProductCode: '{847B014D-B039-32DC-B656-5516376097B3}'
- Architecture: x86
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: 838CB060F846D40C4B9EC8563F79F7DDF0A425AB655C9E9E428D910EEE94170B
  ProductCode: '{3119815A-7DD9-33FF-93CE-1CF03628366E}'
ManifestType: installer
ManifestVersion: 1.1.0
