# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=AUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 98.0.4758.82
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
