# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Mattermost.MattermostDesktop
PackageVersion: 5.0.3
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://releases.mattermost.com/desktop/5.0.3/mattermost-desktop-5.0.3-x64.msi
  InstallerSha256: 40fc234cba9898e583f44563de3b48292872cc8d9ae843c3876a0576a1d2c7bc
  UpgradeBehavior: install
  ProductCode: "{DA84E9A6-6EE5-41D5-8C51-F0209A790EFD}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://releases.mattermost.com/desktop/5.0.3/mattermost-desktop-5.0.3-x86.msi
  InstallerSha256: e721013b9d4dad8bfb5c746ceaab5eae0667c4841488eeb08e92df2611d41c45
  UpgradeBehavior: install
  ProductCode: "{06FED6FE-D089-4CF8-A022-9E59583EA028}"
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: inno
  Scope: user
  InstallerUrl: https://releases.mattermost.com/desktop/5.0.3/mattermost-desktop-setup-5.0.3-win.exe
  InstallerSha256: e2353ccba40bb0a7c69a08981404b2c0a7964a7f6ff63aa5dbeb3dd88f026812
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
