# Created with YamlCreate.ps1 v2.0.6 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Jackett.Jackett
PackageVersion: 0.20.497.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Jackett/Jackett/releases/download/v0.20.497/Jackett.Installer.Windows.exe
  InstallerSha256: 0CF7BFF3927D005EF0B347AE58260346E300D6A429B1DBC208D5C012429EF2DF
ManifestType: installer
ManifestVersion: 1.1.0
