# Automatically updated by the winget bot at 2022/Feb/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Grammarly.ForWindows
PackageVersion: 1.0.2.130
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallerSwitches:
  Silent: /fastforallmode /silent
  SilentWithProgress: /fastforallmode /silent
Installers:
- Architecture: x86
  InstallerUrl: https://download-windows.grammarly.com/GrammarlyInstaller.exe
  InstallerSha256: 2CF00AB93662B42BF74C7541BF4A1660C34368FBCA459431D475074A57271D0F
  ProductCode: Grammarly Desktop Integrations
ManifestType: installer
ManifestVersion: 1.1.0
