# Automatically updated by the winget bot at 2022/Feb/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ksnip.ksnip.Continuous
PackageVersion: 1.10.0
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
UpgradeBehavior: install
FileExtensions:
- bmp
- gif
- jpg
- png
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ksnip/ksnip/releases/download/continuous/ksnip-1.10.0-continuous.msi
  InstallerSha256: 93E056F8832FCF27F1E1E7BFA7DA3B0FC0B088B7E659A6F5037CA639B515FF31
  ProductCode: '{5A81F51D-8CE1-4224-988F-9C0A9AE5C7B1}'
ManifestType: installer
ManifestVersion: 1.1.0
