# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=QUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.Kate
PackageVersion: 21.12.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1563/artifact/kate-21.12.2-1563-windows-msvc2019_64-cl.exe
  InstallerSha256: 040FDD9C865A88786A57BB6493217D2EF3A932820585D4ABB6926FA6AE9C08DA
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1563/artifact/kate-21.12.2-1563-windows-msvc2019_64-cl.exe
  InstallerSha256: 040FDD9C865A88786A57BB6493217D2EF3A932820585D4ABB6926FA6AE9C08DA
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
