# Created with YamlCreate.ps1 v2.0.6 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.umbrello
PackageVersion: 21.12.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
FileExtensions:
- mdl
- xmi
- zargo
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Umbrello_Release_win64/1147/artifact/umbrello-21.12.1-1147-windows-msvc2019_64-cl.exe
  InstallerSha256: 86922359424D8002E6302097D094257786E5435CE8D79890819D154CED61B53F
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Umbrello_Release_win64/1147/artifact/umbrello-21.12.1-1147-windows-msvc2019_64-cl.exe
  InstallerSha256: 86922359424D8002E6302097D094257786E5435CE8D79890819D154CED61B53F
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
