# Automatically updated by the winget bot at 2022/Feb/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: WhatsApp.WhatsApp.Beta
PackageVersion: 2.2205.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/x64/WhatsAppSetup-beta.exe
  InstallerSha256: 54EA322F7F798454CB13996B2C32242D63C0D4523E5D67A9EC8C3E250E6B1768
- Architecture: x86
  InstallerUrl: https://web.whatsapp.com/desktop-beta/windows/release/ia32/WhatsAppSetup-beta.exe
  InstallerSha256: 747113D34B3B0E4FB91AFCA8A2890BFBEF67BE8A2E159F3839C0322C561911FC
ManifestType: installer
ManifestVersion: 1.1.0
