# Automatically updated by the winget bot at 2022/Feb/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SoftPerfect.SoftPerfectNetworkScanner
PackageVersion: 8.1.3
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
FileExtensions:
- xml
- txt
- html
- htm
- csv
- json
- db
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://www.softperfect.com/download/files/netscan_setup.exe
  InstallerSha256: A2F7BA3DA9889E4843695459FEC15FA4B7E71E28F29C97698C98A728C09E9998
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
