# Created with YamlCreate.ps1 v2.0.6 $debug=AUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Blade.Shadow
PackageVersion: 5.0.1072
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://update.shadow.tech/launcher/prod/win/x64/ShadowSetup.exe
  InstallerSha256: C283D09B3AFD43CA3BBBC960BBCD5E4B186A751E2BF5E9799DC78BAB35D81BEC
- Architecture: x86
  InstallerUrl: https://update.shadow.tech/launcher/prod/win/x86/ShadowSetup.exe
  InstallerSha256: BB36F4C5320D49A536B61A155F53F998CF9A4A94CFAA4F0F76100DA49B5DF988
ManifestType: installer
ManifestVersion: 1.1.0
