# Automatically updated by the winget bot at 2022/Feb/10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: F-Secure.Freedome
PackageVersion: 2.45.887.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://download.sp.f-secure.com/freedome/installer/2/Freedome.exe
  InstallerSha256: ED09090F7004A6DC525FE61C157DF61CE60BFC41ED5A0CE09153021A4C008912
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
