# Created with YamlCreate.ps1 v2.0.6 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser.Dev
PackageVersion: 98.1.36.81
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: ' '
  SilentWithProgress: ' '
UpgradeBehavior: install
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.36.81/BraveBrowserStandaloneSilentDevSetup.exe
  InstallerSha256: B07B92A8CF36309B4F5CC7E065976DBAB3EE05C1366A0E3AA8E1A30098CA329D
ManifestType: installer
ManifestVersion: 1.1.0
