# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SonicWALL.NetExtender
PackageVersion: 10.2.322
InstallerSwitches:
  Silent: /quiet /norestart
  SilentWithProgress: /passive /norestart
InstallerSuccessCodes:
- 3010
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  InstallerUrl: https://software.sonicwall.com/NetExtender/NetExtender-x86-10.2.322.MSI
  InstallerSha256: F4B173CD010EF9FB70319044AC30ABD754BCB1C2C01DCCA1BB4391E3B236EE62
  ProductCode: '{EF06A6A8-6B81-4A09-8223-789953972FFF}'
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://software.sonicwall.com/NetExtender/NetExtender-x64-10.2.322.MSI
  InstallerSha256: A1CC0033C4EE7979E0F8817A4E7AA0103ABC9DA59C289289256447CB77AF688F
  ProductCode: '{EF06A6A8-6B81-4A09-8223-789953972FFF}'
ManifestType: installer
ManifestVersion: 1.0.0

