# Created with YamlCreate.ps1 v2.0.6 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: KDE.Kate
PackageVersion: 21.12.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1554/artifact/kate-21.12.1-1554-windows-msvc2019_64-cl.exe
  InstallerSha256: 4D17983897EB2D049357A8320499EAF1D025FE07C2BE68A45D4AED618062D1E2
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/1554/artifact/kate-21.12.1-1554-windows-msvc2019_64-cl.exe
  InstallerSha256: 4D17983897EB2D049357A8320499EAF1D025FE07C2BE68A45D4AED618062D1E2
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0
