# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=QUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser.Dev
PackageVersion: 98.1.36.88
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: ' '
  SilentWithProgress: ' '
UpgradeBehavior: install
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.36.88/BraveBrowserStandaloneSilentDevSetup.exe
  InstallerSha256: 2E7D6C94AE75A03C46F4C1857614913199DCF41AD70BA42574D733558B94C7E2
ManifestType: installer
ManifestVersion: 1.1.0
