# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json
PackageIdentifier: Cisco.WebexTeams
PackageVersion: 42.2.0.21338
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

