# Created with YamlCreate.ps1 v2.0.6 using InputObject 🤖 $debug=QUSU-7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ImageMagick.ImageMagick
PackageVersion: 7.1.0.23
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- bmp
- eps
- gif
- jpg
- mif
- miff
- png
- svg
- tif
- tiff
- wmf
Installers:
- Architecture: x64
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-23-Q16-HDRI-x64-dll.exe
  InstallerSha256: 084F7B56BDFD9382BF774B9122F27DF03B1A8BA6D61CBC702001B55ED9DE2F16
  ProductCode: ImageMagick 7.1.0 Q16-HDRI (64-bit)_is1
- Architecture: x86
  InstallerUrl: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.1.0-23-Q16-HDRI-x86-dll.exe
  InstallerSha256: 1CB605587045F93604955DDE6B5DC910F9A6A18E0641595D5380E078D4D87A8E
  ProductCode: ImageMagick 7.1.0 Q16-HDRI (32-bit)_is1
ManifestType: installer
ManifestVersion: 1.1.0
