# Created with YamlCreate.ps1 v2.0.6 $debug=QUSU.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: GrafanaLabs.GrafanaOSS
PackageVersion: 8.3.5.0
PackageLocale: en-US
Publisher: Grafana Labs
PublisherUrl: https://grafana.com/
PublisherSupportUrl: https://grafana.com/contact/
PrivacyUrl: https://grafana.com/legal/privacy-policy/
Author: Grafana Labs
PackageName: GrafanaOSS
PackageUrl: https://grafana.com
License: GNU Affero General Public License v3.0
LicenseUrl: https://github.com/grafana/grafana/blob/master/LICENSE
Copyright: Copyright 2022 © Grafana Labs
CopyrightUrl: https://github.com/grafana/grafana/blob/master/LICENSE
ShortDescription: Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored. Create, explore, and share dashboards with your team and foster a data driven culture.
# Description: 
Moniker: grafana-oss
Tags:
- dashboard
- data
- grafana
- graph
- metrics
- prometheus
- query
- visualization
# Agreements: 
ReleaseNotes: |
  Features and enhancements
  • Explore: Show scalar data result in a table instead of graph. #44362, @tharun208
  • Table: Makes footer not overlap table content. #44210, @dprokop
  • update snapshots server url. #44563, @DanCech

  Bug fixes
  • CloudMonitoring: Fix resource labels in query editor. #44550, @iwysiu
  • Cursor sync: Apply the settings without saving the dashboard. #44270, @dprokop
ReleaseNotesUrl: https://github.com/grafana/grafana/releases/tag/v8.3.5
ManifestType: defaultLocale
ManifestVersion: 1.1.0
